### ISSUE TITLE
Calendar: crash when creating an event

### ISSUE THREAD

**Issue by aprilmay** [pjgowtham/android_device_oplus_RMX3360#5]
After update to lineage-20.0-20221202-UNOFFICIAL-RMX3360, the default Calendar app crashes when i try to create an event.
Note that i use Davx (DavDroid) as back-end. Also, this issue does not happen using an alternative calendar (Simple Calendar from F-Droid).
Extract from log (is that the relevant part?):
```
--------- beginning of crash
12-05 12:08:59.482  4893  4893 E AndroidRuntime: FATAL EXCEPTION: main
12-05 12:08:59.482  4893  4893 E AndroidRuntime: Process: org.lineageos.etar, PID: 4893
12-05 12:08:59.482  4893  4893 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at java.util.Arrays.stream(Arrays.java:5575)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at com.android.calendar.event.EditEventView.onItemSelected(EditEventView.java:1488)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-05 12:08:59.482  4893  4893 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

_By the way_: thank you SO MUCH @pjgowtham for your efforts and releasing the image here, very happy with LOS on this nice hardware.

**Comment by pjgowtham** [comment]
I just tried creating an event in the calendar app and it worked without issues for me. Maybe it might help if you clear your app data or do a clean flash

**Comment by aprilmay** [comment]
Thanks. For information i updated to the latest version (20230113) and my calendar started working fine again.
